region = "{{region}}"
# dggr_region = "{{dggr_region}}"
dggr_aws_key = "{{dggr_aws_key}}"
dggr_aws_secret = "{{dggr_aws_secret}}"
certificate_domain = "{{certificate_domain}}"
dggr_zone_id = "{{dggr_zone_id}}"
